// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mnwzvtvyauyxwowjjsmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ud3p2dHZ5YXV5eHdvd2pqc21mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTIyOTYsImV4cCI6MjA2Nzg2ODI5Nn0._H-AmuSFj5TdQWlzVeCZ4BOkrr5_yWdPMnXLk3yklQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});